/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorysystemui.userforms;

import com.mycompany.inventorysystemui.querymethods.QueryMethodHandler;
import com.mycompany.inventorysystemui.querymethods.DatabaseConnector;
import com.mycompany.inventorysystemui.userforms.RegisterFormUser;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;

import java.util.Timer;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;

/**
 *
 * @author Danica
 */
public class LoginForm extends javax.swing.JFrame {
    public String username;
    public String firstName;
    public String lastName;
    public JTextField name1;
    private int count;
    public String checkName;
    private String user;

    /**
     * Creates new form Login
     */
    public LoginForm() {
        initComponents();
        lblRemaining.setVisible(false);
        lblRemain.setVisible(false);
        lblAttempt.setText("");
       
       
    }
   
    int counter;
    public static String standUsername;
    // int attempt = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();
        lblRemain = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBoxIcon = new javax.swing.JLabel();
        lblInventory = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        reportTexT = new javax.swing.JLabel();
        showPass = new javax.swing.JCheckBox();
        numbersLabel = new javax.swing.JLabel();
        lblAttempt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister1 = new javax.swing.JButton();

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Mel\\loadingIcon.jpg")); // NOI18N
        jLabel5.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\inventoryDesignIcon.jpg")); // NOI18N

        lblRemaining.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblRemaining.setForeground(new java.awt.Color(255, 102, 102));
        lblRemaining.setText("jLabel6");

        lblRemain.setText("Remaining: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRemain)
                .addGap(4, 4, 4)
                .addComponent(lblRemaining)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRemaining)
                    .addComponent(lblRemain))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 410));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        lblBoxIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\inventory_categories.png")); // NOI18N

        lblInventory.setBackground(new java.awt.Color(0, 0, 0));
        lblInventory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInventory.setText("E - INVENTORY");

        lblUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setText("Username :");

        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setText("yourname01");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblPass.setBackground(new java.awt.Color(0, 0, 0));
        lblPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPass.setText("Password :");

        txtPass.setForeground(new java.awt.Color(153, 153, 153));
        txtPass.setText("password");
        txtPass.setEchoChar('\u0000');
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\profileIcon.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\passIcon.png")); // NOI18N

        loginBtn.setBackground(new java.awt.Color(0, 204, 255));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOG IN");
        loginBtn.setBorderPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        reportTexT.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        reportTexT.setForeground(new java.awt.Color(255, 0, 0));

        showPass.setBackground(new java.awt.Color(255, 255, 255));
        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });

        numbersLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblAttempt.setText("Attempt");

        jLabel2.setText("Don't have an account?");

        btnRegister1.setBackground(new java.awt.Color(102, 102, 102));
        btnRegister1.setForeground(new java.awt.Color(51, 0, 51));
        btnRegister1.setText("Register");
        btnRegister1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnRegister1.setContentAreaFilled(false);
        btnRegister1.setDefaultCapable(false);
        btnRegister1.setFocusPainted(false);
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblBoxIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addComponent(numbersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reportTexT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showPass))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAttempt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBoxIcon))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 229, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(reportTexT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPass))
                    .addComponent(lblAttempt))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(numbersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegister1))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 340, 405));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
        //To go 
        RegisterFormUser toRegister = new RegisterFormUser();
        toRegister.setVisible(true);
        toRegister.setLocationRelativeTo(null);
        setVisible(false);
              
    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        //Use to red the border in the following condition
        Border normal = BorderFactory.createLineBorder(Color.gray);
        if(txtUsername.getText().equals("yourname01")){
            txtUsername.setText(null);
            txtUsername.requestFocus();
            txtUsername.setForeground(Color.black);
            reportTexT.setText("");
            txtUsername.setBorder(normal);
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        if(txtUsername.getText().equals("")){
            txtUsername.setText("yourname01");
            txtUsername.setForeground(Color.gray);
            reportTexT.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
       
        Border normal = BorderFactory.createLineBorder(Color.gray);
        if(txtPass.getText().equals("password")){
            txtPass.setText(null);
            txtPass.requestFocus();
            txtPass.setEchoChar('\u2022');
            txtPass.setForeground(Color.black);
            reportTexT.setText("");
            txtPass.setBorder(normal);
        }
    }//GEN-LAST:event_txtPassFocusGained
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {
        this.requestFocusWindow();
    }
    
    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        // TODO add your handling code here:
        if(txtPass.getText().length()==0){
            txtPass.setText("password");
            txtPass.setEchoChar('\u0000');
            txtPass.setForeground(Color.gray);
            reportTexT.setText("");
        }
    }//GEN-LAST:event_txtPassFocusLost

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
            
            // Create border instances for highlighting input fields in different colors
            Border red = BorderFactory.createLineBorder(Color.red);
            Border normal = BorderFactory.createLineBorder(Color.gray);
            
            // Set user input into username and password variables for further processing
            username = txtUsername.getText();         
            String password = String.valueOf(txtPass.getPassword());
           
            // Check if both username and password match the correct values
            if(username.equals("yourname01") && password.equals("password")){
                 // Display an error message if the fields are empty and highlight them in red
                reportTexT.setText("Fields is empty.");
                txtUsername.setBorder(red);
                txtPass.setBorder(red);      
            }
            
            else if(username.equals("yourname01")){
                reportTexT.setText("Please enter your username");
                txtUsername.setBorder(red);

            }else if(username.isEmpty()){
                reportTexT.setText("Please enter your username");
                txtUsername.setBorder(red);

            }
           else if(username.contains(" ")){
               reportTexT.setText("Seems you accidentally click space!");

           }
           else if(password.equals("password")){
                reportTexT.setText("Please enter your password.");
                txtPass.setBorder(red);
            }else if(password.isEmpty()){
                reportTexT.setText("Please enter your password.");
                txtPass.setBorder(red);
            }
                
                //Display the Dashboard Form
            else{
                txtUsername.setBorder(normal);
                txtPass.setBorder(normal);
                boolean isValid = QueryMethodHandler.loginCheckUser(username,password);
                reportTexT.setText("");
                counter+= 1;
                if(isValid){
                              
                    reportTexT.setText("");  

                    setVisible(false);              
                    counter = 0;
                }              
                else{
                 ///  reportTexT.setText("Invalid user or password");
                   JOptionPane.showMessageDialog(reportTexT,"Invalid user or password(Attempt/s:"+counter+"/3)","Login Denied",JOptionPane.ERROR_MESSAGE);
                   txtUsername.setText("");
                   txtPass.setText("");
                   
                   
                    if(counter==3){                                         
                        try{
                             //program will stop for a minute
        
                            JOptionPane.showMessageDialog(null,"You reached maximum attempts,try again in 1minute!","WARNING",JOptionPane.ERROR_MESSAGE);
                            startCountdown();
                            // reset the counter
                            counter = 0;
                        }
                        catch(Exception e){
                            System.out.println("Interrupted");
                        }

                    }else{
                       // reportTexT.setText("Invalid user or password");
                        

                    }
                }
            }
       
                    
                   
               
            
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if(showPass.isSelected()){
            txtPass.setEchoChar((char)0);
          
            reportTexT.setText("");
        }
        else{
            txtPass.setEchoChar('\u2022');
          

        }

    }//GEN-LAST:event_showPassActionPerformed

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
       
    }//GEN-LAST:event_txtUsernameMouseClicked

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginForm().setVisible(true);
//            }
            //Try
            
      // });
       // }
        
                
                
                
//   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAttempt;
    private javax.swing.JLabel lblBoxIcon;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRemain;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel numbersLabel;
    private javax.swing.JLabel reportTexT;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    //    lblRemaining.setEnable(false);

    private void requestFocusWindow() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
   public boolean addProducts( String product_name,String product_category,Integer product_quantity,String total_price,Integer id,Integer product_price) {
    //   String name = txtUsername.getText();
     
       try (Connection conn = DatabaseConnector.getConnection()) {
            String getUserIdQuery = "SELECT id FROM accounts WHERE username = ?";
            PreparedStatement getUserIdStmt = conn.prepareStatement(getUserIdQuery);
        
            ResultSet rs = getUserIdStmt.executeQuery();
            
            if (rs.next()) {
             //   int id = rs.getInt("id");
               String insertQuery = "INSERT INTO e_table (product_name, product_category, product_quantity, total_price, id, product_price) VALUES (?, ?, ?, ?, ?, ?)";
               getUserIdStmt = conn.prepareStatement(insertQuery);            
                getUserIdStmt.setString(1, product_name);
                getUserIdStmt.setString(2, product_category);
                getUserIdStmt.setInt(3, product_quantity);
                getUserIdStmt.setString(4, total_price);
                getUserIdStmt.setInt(5, id);
                getUserIdStmt.setInt(6, product_price);
                getUserIdStmt.executeUpdate();
               

                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    
     
     }
     private void startCountdown() {
        disableForm();


        count = 59; // Starting number

        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {

            lblRemaining.setVisible(true);
           
            lblRemain.setVisible(true);
            lblRemain.setText("Remaining: ");
           
            lblRemaining.setText(Integer.toString(count));
            count--;

            if (count < 0) {
                ((javax.swing.Timer) e.getSource()).stop();
                lblRemaining.setVisible(false);
                lblRemain.setVisible(false);
                lblRemaining.setText(null);
                enableForm();

                // Perform any desired action after the countdown finishes
            }
        });
        timer.start();
    }
    private void disableForm(){
        txtUsername.setEditable(false);
        txtPass.setEditable(false);
        loginBtn.setEnabled(false);
        showPass.setEnabled(false);
        btnRegister1.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPass.setEnabled(false);
     }
    private void enableForm(){
        txtUsername.setEditable(true);
        txtPass.setEditable(true);
        loginBtn.setEnabled(true);
        btnRegister1.setEnabled(true);
        showPass.setEnabled(true);
        txtUsername.setEnabled(true);
        txtPass.setEnabled(true);

     }
   
   
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
   }


