/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorysystemui.userforms;

import com.mycompany.inventorysystemui.querymethods.QueryMethodHandler;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;



/**
 *
 * @author Danica
 */
public class RegisterFormUser extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterFormUser() {
        initComponents();
//        Connection con;
//        PreparedStatement pst;

    } private static boolean containsNumber(String username) {
        for (char c : username.toCharArray()) {
            if (Character.isDigit(c)) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtConfirmPass = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        btnSignUp = new javax.swing.JButton();
        lblInventory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister2 = new javax.swing.JButton();
        grayPnl = new javax.swing.JPanel();
        reportTxT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNotice = new javax.swing.JLabel();
        lblNotice1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        btnRegister1.setForeground(new java.awt.Color(51, 51, 255));
        btnRegister1.setText("Register");
        btnRegister1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnRegister1.setContentAreaFilled(false);
        btnRegister1.setDefaultCapable(false);
        btnRegister1.setFocusPainted(false);
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstName.setBackground(new java.awt.Color(204, 255, 255));
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 109, 283, 33));

        txtLastName.setBackground(new java.awt.Color(204, 255, 255));
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 182, 283, 33));

        txtEmail.setBackground(new java.awt.Color(204, 255, 255));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 261, 283, 32));

        txtUsername.setBackground(new java.awt.Color(204, 255, 255));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 335, 283, 32));

        txtConfirmPass.setBackground(new java.awt.Color(204, 255, 255));
        txtConfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPassFocusLost(evt);
            }
        });
        txtConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 475, 283, 32));

        txtPass.setBackground(new java.awt.Color(204, 255, 255));
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 407, 283, 32));

        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        jPanel1.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 540, 137, -1));

        btnSignUp.setBackground(new java.awt.Color(0, 204, 255));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(242, 242, 242));
        btnSignUp.setText("SIGN UP");
        btnSignUp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignUp.setBorderPainted(false);
        btnSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSignUpFocusGained(evt);
            }
        });
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 290, 44));

        lblInventory.setBackground(new java.awt.Color(0, 153, 255));
        lblInventory.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblInventory.setText("REGISTER");
        jPanel1.add(lblInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 3, 191, 72));

        jLabel2.setText("Already have an account?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, -1));

        btnRegister2.setBackground(new java.awt.Color(0, 204, 255));
        btnRegister2.setForeground(new java.awt.Color(51, 51, 255));
        btnRegister2.setText("Login");
        btnRegister2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnRegister2.setContentAreaFilled(false);
        btnRegister2.setDefaultCapable(false);
        btnRegister2.setFocusPainted(false);
        btnRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 44, -1));

        grayPnl.setBackground(new java.awt.Color(0, 204, 255));
        grayPnl.setBorder(new javax.swing.border.MatteBorder(null));

        reportTxT.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        reportTxT.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Mel\\register.gif")); // NOI18N

        jLabel3.setText("In service businesses as in others, work can be");

        jLabel4.setText("performed and stored in anticipation of demand. By");

        jLabel5.setText("wisely choosing what kind of inventory to hold,");

        jLabel6.setText("companies can improve quality, response times,");

        jLabel7.setText("customization and pricing.");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Managing Service");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Inventory to Improve");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Performance");

        javax.swing.GroupLayout grayPnlLayout = new javax.swing.GroupLayout(grayPnl);
        grayPnl.setLayout(grayPnlLayout);
        grayPnlLayout.setHorizontalGroup(
            grayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grayPnlLayout.createSequentialGroup()
                .addGap(1041, 1041, 1041)
                .addComponent(reportTxT))
            .addGroup(grayPnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(grayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(grayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        grayPnlLayout.setVerticalGroup(
            grayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grayPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(113, 113, 113)
                .addComponent(reportTxT)
                .addContainerGap())
        );

        jPanel1.add(grayPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 9, 416, 668));

        lblNotice.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lblNotice.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 578, 246, -1));

        lblNotice1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblNotice1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblNotice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 513, 299, 22));

        jLabel12.setText("Confirm Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 451, -1, -1));

        jLabel13.setText("Firstname");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 87, -1, -1));

        jLabel14.setText("Lastname");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 160, -1, -1));

        jLabel15.setText("Email");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 239, -1, -1));

        jLabel16.setText("Username");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 313, -1, -1));

        jLabel17.setText("Password");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 385, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
        //To go
        RegisterFormUser toRegister = new RegisterFormUser();
        toRegister.setVisible(true);
        toRegister.setLocationRelativeTo(null);
        setVisible(false);

    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void btnRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister2ActionPerformed
        // TODO add your handling code here:
        //To go
        new LoginForm().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRegister2ActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
         
       //It is used to record all user data in to the database
        String firstname = txtFirstName.getText();
        String lastname = txtLastName.getText();
        String email = txtEmail.getText();
        String username = txtUsername.getText();
        String password = String.valueOf(txtPass.getPassword());
        String confirmpass = String.valueOf(txtConfirmPass.getPassword());
        boolean isValid = isPasswordValid(password);
        String role = "user";
        // String password = String.valueOf(txtRegisterPass.getPassword());
        if(firstname.equals("")&&lastname.equals("")&&email.equals("")&&username.equals("")&&password.equals("")&&confirmpass.equals("")){
            lblNotice1.setText("Some fields must be empty!");
        }else if(firstname.equals("")) {
            lblNotice1.setText("Please enter your firstname!");

        }else if(lastname.equals("")) {
            lblNotice1.setText("Please enter your lastname!");

        }else if(! containsOnlyLetters(firstname)) {
            lblNotice1.setText("Not a valid firstname");

        }else if(! containsOnlyLetters(lastname)) {
            lblNotice1.setText("Not a valid firstname");

        }else if(email.equals("")) {
            lblNotice1.setText("Please enter your email!");

        }else if(! validEmail(email)){
            lblNotice1.setText("Invalid email address!");

        }
        else if(username.equals("")) {
            lblNotice1.setText("Please enter your username!");

        }else if(password.equals("")) {
            lblNotice1.setText("Please enter your password!");
            
        }else if(confirmpass.equals("")) {
            lblNotice1.setText("Please re-type your password!");

//        }
//        else if(!email.contains("@")) {
//            lblNotice1.setText("Email must contain the @ symbol");
        
        }else if(!containsNumber(username)) {
            lblNotice1.setText("Username must contain any number");

        }else if(username.contains(" ")) {
            lblNotice1.setText("Username must not contain spaces");

        }
        else if(username.length() < 7) {
            lblNotice1.setText("Username must contain  at least 6 characters");

        }else if(password.length() < 8) {
            lblNotice1.setText("Password must contain letters, numbers and 8characters");

        }else if(!containsNumber(password)) {
            lblNotice1.setText("Password must contain the any number");

        }else if( password.equals(isValid)) {
            lblNotice1.setText("Password must contain at least one uppercase letter.");
            
        }      
        else if(! password.equals(confirmpass)){
            lblNotice1.setText("Re-type password didn't match!");
            
        }
        else{

            boolean isExist = QueryMethodHandler.newRegisterUser(firstname,lastname,email,username,password,role);
            if(isExist){
                JOptionPane.showMessageDialog(jPanel1, "Username Exists Already");
            }
            else {
                JOptionPane.showMessageDialog(this, "Registered Successfully!");
                new LoginForm().setVisible(true);
                setVisible(false);
               
            }
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSignUpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpFocusGained

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if(showPass.isSelected()){
            txtConfirmPass.setEchoChar((char)0);
            txtPass.setEchoChar((char)0);
            reportTxT.setText("");
        }
        else{
            txtConfirmPass.setEchoChar('\u2022');
            txtPass.setEchoChar('\u2022');

        }
    }//GEN-LAST:event_showPassActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost

//        if(txtPass.getText().length()==0){
//            txtPass.setText("Password");
//            txtPass.setEchoChar('\u0000');
//            txtPass.setForeground(Color.gray);
//            reportTxT.setText("");
//        }
    }//GEN-LAST:event_txtPassFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained

//        if(txtPass.getText().equals("Password")){
//            txtPass.setText(null);
//            txtPass.requestFocus();
//            txtPass.setEchoChar('\u2022');
//            txtPass.setForeground(Color.black);
//            reportTxT.setText("");
//        }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPassActionPerformed

    private void txtConfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPassFocusLost

//        if(txtConfirmPass.getText().length()==0){
//            txtConfirmPass.setText("Confirm Password");
//            txtConfirmPass.setEchoChar('\u0000');
//            txtConfirmPass.setForeground(Color.gray);
//            reportTxT.setText("");
//        }
    }//GEN-LAST:event_txtConfirmPassFocusLost

    private void txtConfirmPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPassFocusGained

        //Act as placeholder that guided the user
//        if(txtConfirmPass.getText().equals("Confirm Password")){
//            txtConfirmPass.setText(null);
//            txtConfirmPass.requestFocus();
//            txtConfirmPass.setEchoChar('\u2022');
//            txtConfirmPass.setForeground(Color.black);
//            reportTxT.setText("");
//        }
    }//GEN-LAST:event_txtConfirmPassFocusGained

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost

        //To not visible the placeholder
//        if(txtUsername.getText().equals("")){
//            txtUsername.setText("Username");
//            txtUsername.setForeground(Color.gray);
//            reportTxT.setText("");
//        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained

        //Act as placeholder that guided the user
//        if(txtUsername.getText().equals("Username")){
//            reportTxT.setText("");
//            txtUsername.setText(null);
//            txtUsername.requestFocus();
//            txtUsername.setForeground(Color.black);
//        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
//        if(txtEmail.getText().equals("")){
//            txtEmail.setText("Email");
//            txtEmail.setForeground(Color.gray);
//            reportTxT.setText("");
//        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
       
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
      
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusGained
      
    }//GEN-LAST:event_txtLastNameFocusGained

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost

//        if(txtFirstName.getText().equals("")){
//            reportTxT.setText(null);
//            txtFirstName.setText("firstname");
//            // txtFirstName.requestFocus();
//            txtFirstName.setForeground(Color.gray);
//        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusGained
       
    }//GEN-LAST:event_txtFirstNameFocusGained
    
    public static boolean isPasswordValid(String password) {
        // Regular expression pattern to match at least one uppercase letter
        String uppercasePattern = ".*[A-Z].*";
        
        // Create a Pattern object from the regular expression
        Pattern pattern = Pattern.compile(uppercasePattern);
        
        // Create a Matcher object to match the pattern against the password
        Matcher matcher = pattern.matcher(password);
        
        // Check if the password matches the pattern
        return matcher.matches();
    } 
    private boolean containsOnlyLetters(String str) {
        //Use to right format in name
            return str.matches("[a-zA-Z ]+");
        }
    
    public static boolean validEmail(String email){
        //It is a valid format for email
        String format = "^(?!.*[_.]{2})[a-zA-Z0-9._]+@[a-zA-Z0-9]+\\.[a-zA-Z]+$";
        Pattern pattern = Pattern.compile(format);
        Matcher matcher = pattern.matcher(email);
        
        return matcher.matches();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister1;
    private javax.swing.JButton btnRegister2;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel grayPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblNotice;
    private javax.swing.JLabel lblNotice1;
    private javax.swing.JLabel reportTxT;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

  

//    private void addUserToDatabase(String usernameNew, String passwordNew) {
//      RegisterForm myForm = new RegisterForm();// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    
}

