/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorysystemui;


import java.awt.Color;
import java.awt.ComponentOrientation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danica
 */
public class InventoryMainSystemUser extends javax.swing.JFrame {
    
    private Integer productId;
    public JTextField name2;
    int proQty;
    int price1;
    
    


    /**
     * Creates new form TabbedPaneTry
     */
    
    public InventoryMainSystemUser() {
        initComponents();
       
        lblUsername.setVisible(false);
        String menu = lblUser.getText();
        String useracc = menuTab.getText();
        jTabbedPane2.setBackground(Color.ORANGE);
        
        
        
        
    }public void showDataTable(){
        
      
    }public void newTable1(String menu){
        
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        txtProName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        uname1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        priceSpinner = new javax.swing.JSpinner();
        lblUser = new javax.swing.JLabel();
        show = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblInventory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ManageUserAccounts = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblInventory3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        lblName2 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        lblPrice1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lname1 = new javax.swing.JLabel();
        uname2 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        quantitySpn = new javax.swing.JSpinner();
        priceSpn = new javax.swing.JSpinner();
        lblUsername = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblInventory1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableForAdd = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jboxCategory = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        lblGetId = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAreaPrint = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        lblName6 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        lblName7 = new javax.swing.JLabel();
        lblName8 = new javax.swing.JLabel();
        lblPrice2 = new javax.swing.JLabel();
        txtCtg = new javax.swing.JTextField();
        txtQuantity1 = new javax.swing.JTextField();
        txtPrice1 = new javax.swing.JTextField();
        lblPrice3 = new javax.swing.JLabel();
        txtProductName3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTab = new javax.swing.JMenu();
        btnHome = new javax.swing.JMenuItem();
        btnProducts = new javax.swing.JMenuItem();
        btnHelp = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Category:");
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 217, -1, -1));

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("Quantity:");
        jPanel2.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 173, -1, -1));

        lblName3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName3.setForeground(new java.awt.Color(255, 255, 255));
        lblName3.setText("Product Name:");
        jPanel2.add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 173, -1, -1));

        txtProName.setBackground(new java.awt.Color(204, 255, 255));
        txtProName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 174, 146, -1));

        txtCategory.setBackground(new java.awt.Color(204, 255, 255));
        txtCategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 220, 146, -1));

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setForeground(new java.awt.Color(255, 0, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Category", "Quantity", " Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        jTable2.setEnabled(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 316, 566, 119));

        addButton.setBackground(new java.awt.Color(255, 153, 51));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD PRODUCT");
        addButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 276, -1, -1));

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price:");
        jPanel2.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 219, -1, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 140, -1, -1));

        lname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 562, -1, 36));

        uname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uname1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 524, 21, 21));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setToolTipText("");
        jSpinner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 173, 93, -1));

        priceSpinner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        priceSpinner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(priceSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 217, 93, -1));

        lblUser.setText("User");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, -1, -1));

        show.setBackground(new java.awt.Color(0, 102, 255));
        show.setIcon(new javax.swing.ImageIcon("C:\\Mel\\refresh.jpg")); // NOI18N
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 441, 61, 38));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblInventory.setBackground(new java.awt.Color(204, 0, 204));
        lblInventory.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        lblInventory.setForeground(new java.awt.Color(255, 255, 255));
        lblInventory.setText("Inventory Management System");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\inventory.png")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(lblInventory)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(172, 172, 172))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 760, -1));

        jPanel12.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 573, 760, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageUserAccounts.setBackground(new java.awt.Color(255, 153, 0));
        ManageUserAccounts.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        ManageUserAccounts.setMaximumSize(new java.awt.Dimension(42767, 42767));
        ManageUserAccounts.setMinimumSize(new java.awt.Dimension(100, 40));
        ManageUserAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageUserAccountsMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Mel\\Services.png")); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 127));
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 346, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Mel\\Operations.png")); // NOI18N
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 158));

        jPanel15.setBackground(new java.awt.Color(255, 153, 51));
        jPanel15.setForeground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1540, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1540, -1));

        jPanel16.setBackground(new java.awt.Color(255, 153, 0));
        jPanel16.setForeground(new java.awt.Color(0, 255, 255));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\inventory.png")); // NOI18N

        lblInventory3.setBackground(new java.awt.Color(204, 0, 204));
        lblInventory3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        lblInventory3.setForeground(new java.awt.Color(255, 255, 255));
        lblInventory3.setText("E-INVENTORY MANAGEMENT SYSTEM");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Mel\\PUP_Logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel22)
                .addGap(112, 112, 112)
                .addComponent(lblInventory3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblInventory3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 30, 1520, 104));

        addButton2.setBackground(new java.awt.Color(255, 153, 0));
        addButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addButton2.setForeground(new java.awt.Color(255, 255, 255));
        addButton2.setText("GET STARTED");
        addButton2.setBorder(null);
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(addButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 270, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Mel\\help.gif")); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, 340));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("WANT  SOME HELP?");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 130, 50));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLICK HERE!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 260, 50));

        ManageUserAccounts.addTab("FEATURES", jPanel5);

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));
        jPanel13.setForeground(new java.awt.Color(0, 255, 255));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("Category :");
        jPanel13.add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        lblName4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName4.setForeground(new java.awt.Color(255, 255, 255));
        lblName4.setText("Quantity :");
        jPanel13.add(lblName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        lblName5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName5.setForeground(new java.awt.Color(255, 255, 255));
        lblName5.setText("Product Name :");
        jPanel13.add(lblName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        txtProductName.setBackground(new java.awt.Color(204, 255, 255));
        txtProductName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 146, 30));

        addButton1.setBackground(new java.awt.Color(255, 153, 0));
        addButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("ADD PRODUCT");
        addButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        jPanel13.add(addButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 150, 30));

        lblPrice1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrice1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice1.setText("Price :");
        jPanel13.add(lblPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, 30));
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1132, 48, -1, -1));

        lname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel13.add(lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1126, 1560, -1, 36));

        uname2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uname2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel13.add(uname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 1522, 21, 21));
        jPanel13.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1104, 48, 22, 24));

        quantitySpn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quantitySpn.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        quantitySpn.setToolTipText("");
        quantitySpn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(quantitySpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 120, 30));

        priceSpn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceSpn.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        priceSpn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.add(priceSpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 120, 30));

        lblUsername.setText("User");
        jPanel13.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 153, 0));
        jPanel14.setForeground(new java.awt.Color(0, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danica\\Documents\\NetBeansProjects\\JTableInventory_UI\\src\\main\\java\\iconImages\\inventory.png")); // NOI18N

        lblInventory1.setBackground(new java.awt.Color(204, 0, 204));
        lblInventory1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        lblInventory1.setForeground(new java.awt.Color(51, 255, 255));
        lblInventory1.setText("PRODUCT MANAGEMENT");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInventory1)
                .addContainerGap(668, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1390, -1));

        tableForAdd.setAutoCreateRowSorter(true);
        tableForAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableForAdd.setForeground(new java.awt.Color(255, 153, 0));
        tableForAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ", "CATEGORY", "QUANTITY", "PRICE", "TOTAL PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableForAdd.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableForAdd.getTableHeader().setReorderingAllowed(false);
        tableForAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableForAddMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableForAdd);

        jPanel13.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 760, 217));

        jPanel17.setBackground(new java.awt.Color(255, 153, 51));
        jPanel17.setForeground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1450, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 1450, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Note:");
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 40, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Click any product in table to remove.");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 210, -1));

        jboxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Techonology and  Electronics", "Home and Kitchen", "Fashion and Apparel", "Health and Beauty", "Sports and Outdoors", "Foods and Beverages" }));
        jPanel13.add(jboxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, 30));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        btnRemove.setBackground(new java.awt.Color(255, 153, 0));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("REMOVE");
        btnRemove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemove.setEnabled(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(647, Short.MAX_VALUE)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 760, 50));

        lblGetId.setText("id");
        jPanel13.add(lblGetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 830, 10, -1));

        ManageUserAccounts.addTab("ADD PRODUCTS", jPanel13);

        jPanel7.setBackground(new java.awt.Color(51, 153, 255));
        jPanel7.setForeground(new java.awt.Color(0, 255, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));
        jPanel10.setForeground(new java.awt.Color(0, 255, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUCTS INVENTORY");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(908, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        viewTable.setAutoCreateRowSorter(true);
        viewTable.setBackground(new java.awt.Color(255, 153, 0));
        viewTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewTable.setForeground(new java.awt.Color(255, 255, 255));
        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ", "CATEGORY", "QUANTITY", "PRICE", "TOTAL PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        viewTable.getTableHeader().setReorderingAllowed(false);
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(viewTable);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1140, 250));

        jPanel11.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1449, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 740, 1449, -1));

        txtAreaPrint.setEditable(false);
        txtAreaPrint.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaPrint.setColumns(20);
        txtAreaPrint.setRows(5);
        txtAreaPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAreaPrintMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(txtAreaPrint);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 550, 260));

        btnPrint.setBackground(new java.awt.Color(255, 153, 0));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel7.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 170, 40));

        lblName6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName6.setForeground(new java.awt.Color(255, 255, 255));
        lblName6.setText("Product Name :");
        jPanel7.add(lblName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setBackground(new java.awt.Color(204, 255, 255));
        txtTotalPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 146, 30));

        lblName7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName7.setForeground(new java.awt.Color(255, 255, 255));
        lblName7.setText("Category :");
        jPanel7.add(lblName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        lblName8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName8.setForeground(new java.awt.Color(255, 255, 255));
        lblName8.setText("Quantity :");
        jPanel7.add(lblName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, -1, -1));

        lblPrice2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrice2.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice2.setText("Total Price :");
        jPanel7.add(lblPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, 30));

        txtCtg.setEditable(false);
        txtCtg.setBackground(new java.awt.Color(204, 255, 255));
        txtCtg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtCtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 210, 30));

        txtQuantity1.setEditable(false);
        txtQuantity1.setBackground(new java.awt.Color(204, 255, 255));
        txtQuantity1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 146, 30));

        txtPrice1.setEditable(false);
        txtPrice1.setBackground(new java.awt.Color(204, 255, 255));
        txtPrice1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 460, 146, 30));

        lblPrice3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrice3.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice3.setText("Price :");
        jPanel7.add(lblPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, -1, 30));

        txtProductName3.setEditable(false);
        txtProductName3.setBackground(new java.awt.Color(204, 255, 255));
        txtProductName3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(txtProductName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 210, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Mel\\refreshIcon.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Note:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 40, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Click any product in table to print.");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 210, -1));

        ManageUserAccounts.addTab("MY TABLE", jPanel7);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("HOW CAN WE HELP YOU?");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("ACCOUNT MANAGEMENT");

        jLabel26.setText("Username icon is used as menu including buttons which :");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("HomeButton");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Products");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Manage your account");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Logout");

        jLabel31.setText("used to see front page of the user including the system features.");

        jLabel32.setText("to second panel used to add products and also remove.");

        jLabel33.setText("to second panel used to add products and also remove.");

        jLabel34.setText("to second panel used to add products and also remove.");

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Mel\\AccountManagement.png")); // NOI18N

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Mel\\remove1.png")); // NOI18N

        jLabel39.setText("modify it, the just click remove button to proceed.");

        jLabel40.setText("then it automatically appeared in field make sure to not");

        jLabel41.setText("Click any product name in the table you want to delete,");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("REMOVE AN EXISTING PRODUCT?");

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Mel\\ADDCENTER.png")); // NOI18N

        jLabel44.setText("and just click the add product to proceed.");

        jLabel45.setText("Enter the specific product that you want to add,");

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel46.setText("HOW TO ADD PRODUCTS?");

        jLabel47.setIcon(new javax.swing.ImageIcon("C:\\Mel\\AccountManagement.png")); // NOI18N

        jLabel48.setText("to second panel used to add products and also remove.");

        jLabel49.setText("to second panel used to add products and also remove.");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Manage your account");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Logout");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Products");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("HomeButton");

        jLabel51.setText("Username icon is used as menu including buttons which :");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("ACCOUNT MANAGEMENT");

        jLabel16.setText("used to see front page of the user including the system features.");

        jLabel53.setText("to second panel used to add products and also remove.");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(27, 27, 27)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(310, 310, 310))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel51)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel20)))
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel30))))
                .addGap(117, 117, 117))
        );

        ManageUserAccounts.addTab("ABOUT", jPanel19);

        getContentPane().add(ManageUserAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1584, 451, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));

        menuTab.setIcon(new javax.swing.ImageIcon("C:\\Mel\\usernameIcon.jpg")); // NOI18N

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        menuTab.add(btnHome);

        btnProducts.setText("MyTable");
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        menuTab.add(btnProducts);

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        menuTab.add(btnHelp);

        jMenu4.setText("Manage your account");

        jMenuItem6.setText("ChangePassword");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        menuTab.add(jMenu4);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuTab.add(jMenuItem3);

        jMenuBar1.add(menuTab);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
      //  Panel 
      ManageUserAccounts.setSelectedIndex(0);
      
    }//GEN-LAST:event_btnHomeActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ManageUserAccount acc = new ManageUserAccount();
        acc.setVisible(true);
        String username = menuTab.getText();
        acc.setUsername.setText(username);
        acc.jMenu1.setText(username);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        String name11= menuTab.getText();
       // newTable1( name11);
    }//GEN-LAST:event_showActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
           
    }//GEN-LAST:event_addButtonActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        int selectRow = jTable2.getSelectedRow();
        // //txtId.setText(model.getValueAt(selectRow, 0).toString());
        // txtCustomer.setText(model.getValueAt(selectRow, 1).toString());
        //        txtProName.setText(model.getValueAt(selectRow, 2).toString());
        //        txtCategory.setText(model.getValueAt(selectRow, 3).toString());
        //        jSpinner1.setText(model.getValueAt(selectRow, 4).toString());
        //        priceSpinner.setText(model.getValueAt(selectRow, 5).toString());
        //        txtTotalPrice.setText(model.getValueAt(selectRow, 6).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Logout", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            setVisible(false);
        }
        

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        // TODO add your handling code here:
        ManageUserAccounts.setSelectedIndex(2);
        
        
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        
        ManageUserAccounts.setSelectedIndex(3);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void ManageUserAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageUserAccountsMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = new DefaultTableModel(null, new String[]{"PRODUCT","CATEGORY","QUANTITY","PRICE","TOTAL PRICE"}){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make all cells uneditable
            }
        };

        viewTable.setModel(model);
        //  viewTable.setModel(new DefaultTableModel(null,new String[]{"PRODUCT","CATEGORY","QUANTITY","PRICE","TOTAL PRICE"}));
        //        @Override
        //        public boolean isCellEditable(int row, int column) {
            //            return false; // Disable cell editing
            displayTable();

    }//GEN-LAST:event_ManageUserAccountsMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        displayAddProduct();
        txtAreaPrint.setText("");
        txtProductName3.setText("");
        txtCtg.setText("");
        txtQuantity1.setText("");
        txtTotalPrice.setText("");
        txtPrice1.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        int selectRow1 = viewTable.getSelectedRow();

        //txtProductName.setText(model1.getValueAt(selectRow1, 0).toString());
        String clickValue = viewTable.getValueAt(selectRow1, 0).toString();

        String pname = txtProductName3.getText();

        if(pname.equals("")){
            JOptionPane.showMessageDialog(null,"Please select any product in table to remove");
        }else if(! pname.equals(clickValue)){
            JOptionPane.showMessageDialog(null, "Not your product, please click any product in table to remove");
        }else{
            try {

                // txtAreaPrint.setText("\t\t\tE-INVENTORY \n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "                     \t\t     E-INVENTORY \n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "                     \t\t     537/Kalilayan Ibaba, \n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "                    \t\t    Unisan, Quezon, \n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "                       \t\t    +63 9658202014 \n\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "------------------------------------------------------------------------------------------------------------------------------------\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "Item to Receipt\nItem \tCategory \t\tQuantity \tPrice\tTotal Price" +"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "------------------------------------------------------------------------------------------------------------------------------------\n");

                DefaultTableModel df = (DefaultTableModel) viewTable.getModel();

                // get table Product details

                for (int i = 0; i < viewTable.getRowCount(); i++) {
                    //                txtProductName3.setText(model.getValueAt(selectRow, 0).toString());
                    //                txtCtg.setText(model.getValueAt(selectRow, 1).toString());
                    //                txtQuantity1.setText(model.getValueAt(selectRow, 2).toString());
                    //                txtPrice1.setText(model.getValueAt(selectRow, 3).toString());
                    //                txtTotalPrice.setText(model.getValueAt(selectRow, 4).toString());
                    String Name = df.getValueAt(i, 0).toString();
                    String Category = df.getValueAt(i, 1).toString();
                    String Price = df.getValueAt(i, 2).toString();
                    String Qty1 = df.getValueAt(i, 3).toString();
                    String Price1 = df.getValueAt(i, 4).toString();

                    txtAreaPrint.setText(txtAreaPrint.getText() +"  "+ Name+"\t"+Category +"\t"+Price +"\t"+Qty1 +"\t"+Price1 + "\n");
                }
                //            DefaultTableModel model = (DefaultTableModel) viewTable.getModel();
                //            int column = 4; // Assuming the price column is at index 3
                //            double sum = 0.0;
                //
                //            for (int row = 0; row < model.getRowCount(); row++) {
                    //                Object value = model.getValueAt(row, column);
                    //                if (value instanceof Number) {
                        //                    sum += ((Number) value).doubleValue();
                        //                }
                    //                String total = String.valueOf(sum);
                    //                txtTotalPrice.setText(total);
                    //            }

                txtAreaPrint.setText(txtAreaPrint.getText() + "-----------------------------------------------------------------------------------------------------------------------------------\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "Your Product : " + txtProductName3.getText() +"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "Category      : " + txtCtg.getText() +"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "Quantity   : " + txtQuantity1.getText().toString() +"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "Price : " + txtPrice1.getText().toString() +"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "Total Price      : " +  txtTotalPrice.getText().toString() +"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "-----------------------------------------------------------------------------------------------------------------------------------\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "                    \t\t Thanks For Your Business...!"+"\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "-----------------------------------------------------------------------------------------------------------------------------------\n");
                txtAreaPrint.setText(txtAreaPrint.getText() + "                   \t\t  E-INVENTORY | 2023"+"\n");

                txtAreaPrint.print(); //print
                btnPrint.setEnabled(false);

            } catch (Exception e) {

                System.out.println(e);

            }
        }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtAreaPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaPrintMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtAreaPrintMouseClicked

    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        btnPrint.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel)viewTable.getModel();
        int selectRow = viewTable.getSelectedRow();

        txtProductName3.setText(model.getValueAt(selectRow, 0).toString());
        txtCtg.setText(model.getValueAt(selectRow, 1).toString());
        txtQuantity1.setText(model.getValueAt(selectRow, 2).toString());
        txtPrice1.setText(model.getValueAt(selectRow, 3).toString());
        txtTotalPrice.setText(model.getValueAt(selectRow, 4).toString());

    }//GEN-LAST:event_viewTableMouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // DefaultTableModel model1 = (DefaultTableModel)tableForAdd.getModel();
        int selectRow1 = tableForAdd.getSelectedRow();

        //txtProductName.setText(model1.getValueAt(selectRow1, 0).toString());
        String clickValue = tableForAdd.getValueAt(selectRow1, 0).toString();

        String pname = txtProductName.getText();

        if(pname.equals("")){
            JOptionPane.showMessageDialog(null,"Please select any product in table to remove");
        }else if(! pname.equals(clickValue)){
            JOptionPane.showMessageDialog(null, "Not your product, please click any product in table to remove");
        }else{
            int choice = JOptionPane.showConfirmDialog(null, "Are you want to remove this product?", "Remove Product", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                String sql ="delete FROM e_products WHERE product_name =? ";
                try(Connection conn = DatabaseConnector.getConnection()){
                    PreparedStatement pstdelete = conn.prepareStatement(sql);
                    pstdelete.setString(1,txtProductName.getText());
                    pstdelete.execute();
                    JOptionPane.showMessageDialog(null,"Product Removed Successfully!");
                    tableForAdd.setModel(new DefaultTableModel(null,new String[]{"PRODUCT","CATEGORY","QUANTITY","PRICE","TOTAL PRICE"}));
                    displayAddProduct();
                    viewTable.setModel(new DefaultTableModel(null,new String[]{"PRODUCT","CATEGORY","QUANTITY","PRICE","TOTAL PRICE"}));
                    displayTable();
                    txtProductName.setText("");
                    btnRemove.setEnabled(false);

                    //   showDataTable();
                }catch(Exception e){

                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tableForAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableForAddMouseClicked
        // TODO add your handling code here:
        btnRemove.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel)tableForAdd.getModel();
        int selectRow = tableForAdd.getSelectedRow();

        txtProductName.setText(model.getValueAt(selectRow, 0).toString());

    }//GEN-LAST:event_tableForAddMouseClicked

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed

        String table = menuTab.getText();

        String name1 = null;

        //To get the user input

        LoginForm lgn = new LoginForm();
        name2 = new JTextField();

        String proname = txtProductName.getText();

        String selectItem = "Select";

        proQty = (int) quantitySpn.getValue();
        price1 = (int) priceSpn.getValue();

        String proQty1 = String.valueOf(proQty);
        String proPrice = String.valueOf(price1);
        Object boxCty = jboxCategory.getSelectedItem();
        String boxCty1 = boxCty.toString();
        double totalprice1 = price1 * proQty;
        String totalprice = String.valueOf(totalprice1);

        if(proname.equals("")&&boxCty.equals("Select")&&proQty1.equals("")){
            JOptionPane.showMessageDialog(null,"All data required");
        }else if(proname.equals("")){
            JOptionPane.showMessageDialog(null,"Product Name Required");
        }else if(boxCty1.equals("Select")){
            JOptionPane.showMessageDialog(null,"Product Category Required");
        }else if(proQty1.equals("")){
            JOptionPane.showMessageDialog(null,"Product Quantity Required");
        }else if(proPrice.equals("")){
            JOptionPane.showMessageDialog(null,"Product Price Required");
        }else if((price1 < 0 )){
            JOptionPane.showMessageDialog(null,"Price Cannot be 0");
        }else if(proQty < 0 ){
            JOptionPane.showMessageDialog(null,"Quantity Cannot be 0");
        }
        else{

            String user_acc1 = menuTab.getText();
            //String id1 = null;

            try(Connection conn = DatabaseConnector.getConnection()){

                String getId =" SELECT id FROM accounts WHERE username = '" + user_acc1 + "'";

                PreparedStatement stmt = conn.prepareStatement(getId);
                //                stmt.setString(1,user_acc1);
                ResultSet rs = stmt.executeQuery();
                if(rs.next()){

                    int column_id = rs.getInt("id");
                    String column_id1 = String.valueOf(column_id);
                    // lblGetId.setText(column_id1);
                    QueryMethodHandler.addTry( user_acc1,proname, boxCty1, proQty, price1, totalprice,column_id);
                }

            }catch (SQLException e1) {
                JOptionPane.showMessageDialog(null, e1);
                e1.printStackTrace();

            }

            txtProductName.setText("");
            jboxCategory.setSelectedItem(selectItem);
            quantitySpn.setValue(1);
            priceSpn.setValue(1);
            //int reply = JOptionPane.showConfirmDialog(null, JOptionPane.YES_NO_OPTION);

            JOptionPane.showMessageDialog(this, "Product Added Successfully!");
            tableForAdd.setModel(new DefaultTableModel(null,new String[]{"PRODUCT","CATEGORY","QUANTITY","PRICE","TOTAL PRICE"}));
            
            displayAddProduct();
        }

    }//GEN-LAST:event_addButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ManageUserAccounts.setSelectedIndex(3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
        ManageUserAccounts.setSelectedIndex(1);
    }//GEN-LAST:event_addButton2ActionPerformed
    public void displayAddProduct(){
        String useracc = lblUsername.getText();
        try (Connection conn = DatabaseConnector.getConnection()) {
            String sql = "SELECT p.*FROM e_products p WHERE p.id IN (SELECT u.id FROM accounts u WHERE u.username = ?);";
            PreparedStatement stmt = conn.prepareStatement(sql);
           
            stmt.setString(1, useracc);
               ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                   
                    String product = rs.getString("product_name");
                    String category = rs.getString("product_category");
                    String quantity =  String.valueOf(rs.getString("product_quantity"));
                    String price =  String.valueOf(rs.getString("product_price"));
                    String total =  String.valueOf(rs.getString("total_price"));
                    // Do something with the data
                    String dataProducts[] = {product,category,quantity,price,total};
                    DefaultTableModel tblModel = (DefaultTableModel)tableForAdd.getModel();
                    tblModel.addRow(dataProducts);
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection error: " +
                e.getMessage());
        }
    }

    /**
     *
     */
    public void displayTable(){
        
        String useracc = lblUsername.getText();
        try (Connection conn = DatabaseConnector.getConnection()) {
            String sql = "SELECT p.*FROM e_products p WHERE p.id IN (SELECT u.id FROM accounts u WHERE u.username = ?);";
                        
            PreparedStatement stmt = conn.prepareStatement(sql);
          
            stmt.setString(1, useracc);
               ResultSet rs = stmt.executeQuery();
                while (rs.next()) {
                                       
                    String product = rs.getString("product_name");
                    String category = rs.getString("product_category");
                    String quantity =  String.valueOf(rs.getString("product_quantity"));
                    String price =  String.valueOf(rs.getString("product_price"));
                    String total =  String.valueOf(rs.getString("total_price"));
                    // Do something with the data
                    String dataProducts[] = {product,category,quantity,price,total};
                    DefaultTableModel tblModel = (DefaultTableModel)viewTable.getModel();
                    tblModel.addRow(dataProducts);
                
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database connection error: " +
                e.getMessage());
        }
   

  
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryMainSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryMainSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryMainSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryMainSystemUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryMainSystemUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ManageUserAccounts;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addButton2;
    private javax.swing.JMenuItem btnHelp;
    private javax.swing.JMenuItem btnHome;
    private javax.swing.JButton btnPrint;
    private javax.swing.JMenuItem btnProducts;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private static javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jboxCategory;
    public static javax.swing.JLabel lblGetId;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblInventory1;
    private javax.swing.JLabel lblInventory3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblPrice2;
    private javax.swing.JLabel lblPrice3;
    public static javax.swing.JLabel lblUser;
    public static javax.swing.JLabel lblUsername;
    public static javax.swing.JLabel lname;
    public static javax.swing.JLabel lname1;
    public javax.swing.JMenu menuTab;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JSpinner priceSpn;
    private javax.swing.JSpinner quantitySpn;
    private javax.swing.JButton show;
    private javax.swing.JTable tableForAdd;
    private javax.swing.JTextArea txtAreaPrint;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCtg;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtProName;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductName3;
    private javax.swing.JTextField txtQuantity1;
    private javax.swing.JTextField txtTotalPrice;
    public javax.swing.JLabel uname;
    public static javax.swing.JLabel uname1;
    public static javax.swing.JLabel uname2;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
